"""empty message

Revision ID: 6b081f193774
Revises: 
Create Date: 2021-03-12 13:55:24.997323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b081f193774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=128), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(length=128), nullable=False),
    sa.Column('avail', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    # ### end Alembic commands ###
